Import('localenv')
localenv.Append(CXXFLAGS=['-DQUANTITY_AoS'])

localenv = localenv.Clone()

#Specialize environment

objs = []
# build sources
srcs = Glob('*.cpp')
o = localenv.Object(srcs)
objs.append(o)

Return('objs')
