Import('localenv')
localenv = localenv.Clone()

# build sources only if this is not in sequential mode.
if '-DSEQUENTIAL' not in localenv['CXXFLAGS']:
    srcs = Glob('*.cpp')
    objs = localenv.Object(srcs)
    Return('objs')

Return()
