Import('localenv')
localenv = localenv.Clone()

#Specialize environment
#objs = SConscript('convexhull/SConscript', exports = 'localenv')
#objs.append(SConscript('decimal/SConscript', exports = 'localenv'))
#objs.append(SConscript('optionchain/SConscript', exports = 'localenv'))
#objs.append(SConscript('historicalrequest/SConscript', exports = 'localenv'))
#objs.append(SConscript('commandhandler/SConscript', exports = 'localenv'))

objs = []
# build sources
srcs = Glob('*.cpp')
o = localenv.Object(srcs)
objs.append(o)

Return('objs')
