Import('localenv')
localenv = localenv.Clone()

#Specialize environment
objs = SConscript('timestamp/SConscript', exports = 'localenv')
objs.append(SConscript('timer/SConscript', exports = 'localenv'))
objs.append(SConscript('exception/SConscript', exports = 'localenv'))
objs.append(SConscript('threadpool/SConscript', exports = 'localenv'))
objs.append(SConscript('number/SConscript', exports = 'localenv'))

# build sources
srcs = Glob('*.cpp')
o = localenv.Object(srcs)
objs.append(o)

Return('objs')
